### PR TITLE
fix: use aggregate_current for SIMILAR total type in percentile calc

### LINKED ISSUE #6470: Why do the aggregated ports in Figure 1 have the same input and output directions (95 values), while the single-port ports in Figure 2 work normally? What could be the reason for this?
```
RRDtool 命令:
/usr/local/bin/rrdtool graph - \
--imgformat=SVG \
--start='1763470020' \
--end='1763556420' \
--pango-markup  \
--title='test' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=200 \
--width=700 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 2025-11-18 20\:47\:00 To 2025-11-19 20\:47\:00\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 \
--font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
--watermark 'Generated by Cacti®' \
DEF:a='/var/www/html/cacti/rra/d__traffic_in_6045.rrd':'traffic_in':MAX \
DEF:b='/var/www/html/cacti/rra/d__traffic_in_6045.rrd':'traffic_in':AVERAGE \
DEF:c='/var/www/html/cacti/rra/d__traffic_in_6045.rrd':'traffic_out':AVERAGE \
DEF:d='/var/www/html/cacti/rra/d__traffic_in_6046.rrd':'traffic_in':MAX \
DEF:e='/var/www/html/cacti/rra/d__traffic_in_6046.rrd':'traffic_in':AVERAGE \
DEF:f='/var/www/html/cacti/rra/d__traffic_in_6046.rrd':'traffic_out':AVERAGE \
CDEF:cdefa='a,8,*' \
CDEF:cdefb='b,8,*' \
CDEF:cdefe='c,8,*' \
CDEF:cdefi='d,8,*' \
CDEF:cdefj='e,8,*' \
CDEF:cdefbc='f,8,*' \
CDEF:cdefbh='TIME,1763560185,GT,b,b,UN,0,b,IF,IF,TIME,1763560185,GT,e,e,UN,0,e,IF,IF,+,8,*' \
CDEF:cdefcb='TIME,1763560185,GT,c,c,UN,0,c,IF,IF,TIME,1763560185,GT,f,f,UN,0,f,IF,IF,+,8,*' \
AREA:cdefa#00CF00FF:'100GE1/0/5'  \
AREA:cdefb#00CF007F:'100GE1/0/5'  \
GPRINT:cdefb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefb:AVERAGE:'Average\:%8.2lf %s\n'  \
AREA:cdefe#002A977F:'100GE1/0/5'  \
GPRINT:cdefe:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefe:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefe:MAX:'Maximum\:%8.2lf %s\n'  \
AREA:cdefi#00CF00FF:'100GE1/0/6':STACK \
AREA:cdefj#00CF007F:'100GE1/0/6':STACK \
GPRINT:cdefj:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefj:AVERAGE:'Average\:%8.2lf %s\n'  \
AREA:cdefbc#002A977F:'100GE1/0/6':STACK \
GPRINT:cdefbc:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefbc:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefbc:MAX:'Maximum\:%8.2lf %s\n'  \
COMMENT:' \n'  \
LINE1:cdefbh#00CF00FF: \
LINE1:cdefbh#00CF007F:'一共    ' \
GPRINT:cdefbh:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefbh:AVERAGE:'Average\:%8.2lf %s\n'  \
LINE1:cdefcb#002A977F: \
GPRINT:cdefcb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefcb:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefcb:MAX:'Maximum\:%8.2lf %s\n'  \
COMMENT:' \n'  \
HRULE:6800445196.8#FF0000FF:'95th Percentile' \
COMMENT:'(6800.45 mbit out)'  \
HRULE:6800445196.8#EA8F00FF:'95th Percentile' \
COMMENT:'(6800.45 mbit in)' 
RRDtool Command lengths = 2624 characters.
RRDtool 说:
SVG/XML Output OK
```

Image

```
RRDtool 命令:
/usr/local/bin/rrdtool graph - \
--imgformat=SVG \
--start='1763470020' \
--end='1763556420' \
--pango-markup  \
--title='test111 ' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=200 \
--width=700 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 2025-11-18 20\:47\:00 To 2025-11-19 20\:47\:00\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 \
--font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
--watermark 'Generated by Cacti®' \
DEF:a='/var/www/html/cacti/rra/d__traffic_in_6045.rrd':'traffic_in':MAX \
DEF:b='/var/www/html/cacti/rra/d__traffic_in_6045.rrd':'traffic_in':AVERAGE \
DEF:c='/var/www/html/cacti/rra/d__traffic_in_6045.rrd':'traffic_out':MAX \
DEF:d='/var/www/html/cacti/rra/d__traffic_in_6045.rrd':'traffic_out':AVERAGE \
CDEF:cdefa='a,8,*' \
CDEF:cdefb='b,8,*' \
CDEF:cdeff='c,8,*' \
CDEF:cdefg='d,8,*' \
LINE1:cdefa#00CF00FF: \
AREA:cdefb#00CF007F:'Inbound '  \
GPRINT:cdefb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefb:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefb:MAX:'Maximum\:%8.2lf %s\n'  \
LINE1:cdeff#002A97FF: \
AREA:cdefg#002A977F:'Outbound'  \
GPRINT:cdefg:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefg:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefg:MAX:'Maximum\:%8.2lf %s\n'  \
COMMENT:' \n'  \
HRULE:1306735518.08#FF0000FF:'95th Percentile' \
COMMENT:'(1306.74 mbit out)'  \
HRULE:2495804862.32#EA8F00FF:'95th Percentile' \
COMMENT:'(2495.8 mbit in)' 
RRDtool Command lengths = 1674 characters.
RRDtool 说:
SVG/XML Output OK
```

Image

cacti version 1.2.30

Why do the aggregated ports in Figure 1 have the same input and output directions (95 values), while the single-port ports in Figure 2 work normally? What could be the reason for this?

### PR DESCRIPTION
**Pull request by somethingwithproof**
## Summary
- SIMILAR total type was using `aggregate_sum` functions (same as ALL), instead of per-data-source `aggregate_current`
- Separates SIMILAR from ALL in three code paths in `lib/api_aggregate.php`
- SIMILAR now uses `:aggregate_current:` and `:aggregate_current_peak:` for correct per-source percentile

Closes #6470

## Test plan
- [ ] Verify `AggregatePtileTypeTest.php` passes
- [ ] Confirm SIMILAR aggregate graphs show per-data-source percentile, not summed

### CODE REVIEW

File: lib/functions.php [hunk 1]
```diff
@@ -3885,7 +3885,7 @@ function get_graph_parent(int $graph_template_item_id, string $direction) : int
 			ORDER BY sequence $sql_order
 			LIMIT 1");
 	} else {
-		$next_parent_it = 0;
+		$next_parent_id = 0;
```
Comment (TheWitness) [inline lib/functions.php:3888]: Good catch here.  Ugh!  Stan should have picked this up.  Wonder why it did not.

**Review by TheWitness — CHANGES_REQUESTED** [review]
Fix the merge conflicts and this is good.

**Comment by somethingwithproof** [comment]
Fixed.

**Comment by somethingwithproof** [comment]
Conflicts resolved, please re-review.

**Review by TheWitness — APPROVED** [review]
