### PR TITLE
fix(security): harden auth lockout, CSPRNG fallback, error escaping, and redirect (1.2.x)

### LINKED ISSUE #6996: security: TOCTOU race in auth_process_lockout allows brute-force lockout bypass
## Description
`auth_process_lockout()` reads `failed_attempts` in PHP, increments it, evaluates the threshold, then writes it back. Parallel requests all read the same stale value, bypassing the lockout threshold.

## Impact
Brute-force attack with concurrent requests can bypass account lockout entirely.

## Remediation
Use atomic `UPDATE user_auth SET failed_attempts = failed_attempts + 1` and evaluate the threshold after the atomic increment.

### LINKED ISSUE #6997: hardening: remove predictable mt_rand fallback in set_auth_cookie
## Description
In `set_auth_cookie()`, if `random_bytes()` throws an exception, the code falls back to `md5($_SERVER['REQUEST_TIME'] . mt_rand(...))` which is predictable and allows session token forgery.

## Impact
If the system CSPRNG is unavailable, authentication cookies become predictable.

## Remediation
Remove the catch fallback. If `random_bytes()` fails, fail closed by not setting the cookie.

### LINKED ISSUE #6998: hardening: escape error message output in auth_display_custom_error_message
## Description
`auth_display_custom_error_message()` prints `$message` directly into the DOM without HTML escaping. When the message originates from LDAP error responses, a compromised LDAP server can inject arbitrary HTML/JS.

## Impact
Reflected XSS via LDAP error text injection.

## Remediation
Escape `$message` with `htmlspecialchars()` before rendering.

### LINKED ISSUE #6999: hardening: use validate_redirect_url for REDIRECT_URL in auth_login_redirect
## Description
`auth_login_redirect()` reads `$_SERVER['REDIRECT_URL']` and redirects to it after sanitization. If `sanitize_uri()` does not enforce relative paths (reject `//` prefix, external schemes), this allows open redirect.

## Impact
Post-login phishing via open redirect.

## Remediation
Enforce that the redirect URL starts with `/` and does not start with `//`.

### PR DESCRIPTION
**Pull request by somethingwithproof**
## Summary
Four targeted security fixes in `lib/auth.php`:

1. **TOCTOU lockout bypass** (#6996): atomic `failed_attempts = failed_attempts + 1` prevents concurrent brute-force requests from bypassing the lockout threshold
2. **CSPRNG fallback** (#6997): remove predictable `mt_rand()` fallback in `set_auth_cookie()`; fail closed if `random_bytes()` is unavailable
3. **XSS in error display** (#6998): escape `$message` and `$custom_message` with `htmlspecialchars()` in `auth_display_custom_error_message()`
4. **Open redirect** (#6999): enforce relative path validation on `REDIRECT_URL` (reject protocol-relative `//` URLs)

Closes #6996, closes #6997, closes #6998, closes #6999

## Test plan
- [ ] Verify login lockout triggers correctly after N failed attempts
- [ ] Verify remember-me cookie is not set if CSPRNG fails
- [ ] Verify LDAP error messages render as text, not HTML
- [ ] Verify post-login redirect works for valid relative paths
- [ ] Verify `//evil.com` in REDIRECT_URL redirects to index.php instead

### CODE REVIEW

File: lib/auth.php [hunk 1]
```diff
@@ -3542,30 +3544,44 @@ function auth_process_lockout_check($username, $realm) {
...
 					$error     = true;
 					$error_msg = __('Access Denied!  Login Disabled.');
+
+					return;
 				}
 
-				$failed = intval($user['failed_attempts']) + 1;
+				/* Atomic increment to prevent TOCTOU race in concurrent requests */
+				db_execute_prepared("UPDATE user_auth
+					SET lastfail = ?, failed_attempts = failed_attempts + 1
```
[the remark this answers is not in the document]
Comment (somethingwithproof) [reply lib/auth.php]: Fixed. Moved lockout increment before the disabled check so disabled accounts still accumulate failed attempts.

File: lib/auth.php [hunk 2]
```diff
@@ -3542,30 +3544,44 @@ function auth_process_lockout_check($username, $realm) {
...
+					AND realm = ?
+					AND enabled = 'on'",
+					array(time(), $username, $realm));
 
-				cacti_log('LOGIN FAILED: User \'' . $username . '\' failed authentication, incrementing lockout (' . $failed . ' of ' . $max . ')', false, 'AUTH', POLLER_VERBOSITY_LOW);
+				/* Retrieve deterministic state post-increment */
+				$failed = db_fetch_cell_prepared("SELECT failed_attempts
+					FROM user_auth
+					WHERE username = ?
+					AND realm = ?",
```
[the remark this answers is not in the document]
Comment (somethingwithproof) [reply lib/auth.php]: Fixed. Added enabled filter to the re-read query.

File: lib/auth.php
[the remark this answers is not in the document]
Comment (somethingwithproof) [reply lib/auth.php]: The validate_redirect_url() function in html_utility.php (updated in #7002) handles the primary validation. The REDIRECT_URL check here is a defense-in-depth layer.

File: lib/auth.php [hunk 3]
```diff
@@ -4631,7 +4636,7 @@ function auth_display_custom_error_message($message) {
 
 	print '</head>';
 	print '<body><center>';
-	print '<div class="ui-state-error ui-corner-all" style="width:50%;margin-left:auto;margin-right:auto;margin-top:200px;padding:20px"><p>' . $message . '</p><p>' . $custom_message . '</p></div>';
+	print '<div class="ui-state-error ui-corner-all" style="width:50%;margin-left:auto;margin-right:auto;margin-top:200px;padding:20px"><p>' . htmlspecialchars($message, ENT_QUOTES, 'UTF-8') . '</p><p>' . htmlspecialchars($custom_message, ENT_QUOTES, 'UTF-8') . '</p></div>';
```
Comment (TheWitness) [inline lib/auth.php]: Use html_escape() and not htmlspecialchars()

File: lib/auth.php [hunk 4]
```diff
@@ -3576,35 +3592,24 @@ function auth_process_lockout($username, $realm) {
...
-
-				// Log the invalid password attempt
 				db_execute_prepared('INSERT IGNORE INTO user_log
 					(username, user_id, result, ip, time)
 					VALUES (?, ?, 0, ?, NOW())',
 					array($username, isset($user['id']) ? $user['id']:0, get_client_addr()));
 
 				if ($user['locked'] == 'on') {
-					cacti_log("LOGIN FAILED: Local Login Failed for user '" . $username . "' from IP Address '" . get_client_addr() . "'.  Account is locked out.", false, 'AUTH');
+					cacti_log("LOGIN FAILED: Local Login Failed for user '" . $username . "'. Account is locked out.", false, 'AUTH');
```
Comment (TheWitness) [inline lib/auth.php]: Why are you removing the client address in this pull in three areas?

File: lib/auth.php [hunk 5]
```diff
@@ -4673,6 +4678,12 @@ function auth_login_redirect($login_opts = '') {
 			if (isset($_SERVER['REDIRECT_URL'])) {
 				$referer = sanitize_uri($_SERVER['REDIRECT_URL']);
 
+				/* Enforce relative path to prevent open redirect via
```
Comment (TheWitness) [inline lib/auth.php]: Why not use our newly minted redirect function?

File: lib/auth.php
[the remark this answers is not in the document]
Comment (TheWitness) [reply lib/auth.php]: Why is that not covered in the generic function then?

**Review by TheWitness — CHANGES_REQUESTED** [review]

File: lib/auth.php (hunk 3 above)
Comment (somethingwithproof) [reply lib/auth.php]: Fixed.

File: lib/auth.php (hunk 4 above)
Comment (somethingwithproof) [reply lib/auth.php]: Fixed.

File: lib/auth.php (hunk 5 above)
Comment (somethingwithproof) [reply lib/auth.php]: Fixed.

File: lib/auth.php
[the remark this answers is not in the document]
Comment (somethingwithproof) [reply lib/auth.php]: Fixed.

**Review by TheWitness — APPROVED** [review]

**Comment by TheWitness** [comment]
If you cherry pick this one into develop, it'll fail phpcsfixer.  But your pre-commit hook should resolve it automatically.  It'll be a good test.
