### PR TITLE
Fixes issue 1814

### LINKED ISSUE #1814: [1.2.0] - db_echo_sql calls wrong function name get_sys_temp_dir()
https://github.com/Cacti/cacti/blob/147c152eb7ef6d7d5649c42703d1ec23bf929efc/lib/database.php#L1282
must be:
**sys_get_temp_dir()**
`file_put_contents(sys_get_temp_dir() . '/cacti-sql.log', get_debug_prefix() . $line, FILE_APPEND);`

### PR DESCRIPTION
**Pull request by pautiina**
Fix #1814

### CODE REVIEW

File: lib/database.php [hunk 1]
```diff
@@ -1279,6 +1279,6 @@ function db_echo_sql($line, $force = false) {
 	global $config;
 
 	if (!empty($config['DEBUG_SQL_FLOW'])) {
-		file_put_contents(get_sys_temp_dir() . '/cacti-sql.log', get_debug_prefix() . $line, FILE_APPEND);
+		file_put_contents(sys_get_temp_dir() . '/cacti-sql.log', get_debug_prefix() . $line, FILE_APPEND);
```
Comment (netniV) [inline lib/database.php]: Oh my bad.  Typo there

Comment (pautiina) [reply lib/database.php]: :)
